version: "3"
services:
  frontend:
    image: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: backend
    ports:
      - "5000:5000"
    restart: always
