version: "3"
services:
  frontend:
    image: asia.gcr.io/pacific-element-296717/frontend
    stdin_open: true
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: asia.gcr.io/pacific-element-296717/backend
    ports:
      - "5000:5000"
    restart: always
